version: '3.7'

volumes:
  postgres:
  mlflow:
  prefect:

networks:
  backend:
  frontend:

services:
  tracking-server-db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend
    ports:
      - 5432:5432
    restart: always

  mlflow:
    image: mlflow_tracking_server
    build:
      context: ./monitoring/mlflow
      dockerfile: Dockerfile
    volumes:
      - mlflow:/var/lib/mlflow/data
    networks:
      - backend
      - frontend
    ports:
      - 5000:5000
    depends_on:
      - tracking-server-db
    restart: always
    command: mlflow server --backend-store-uri postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@tracking-server-db:5432/${POSTGRES_DB} --default-artifact-root /var/lib/mlflow/data/mflow/ --host 0.0.0.0

  prefect:
    image: prefecthq/prefect:2-python3.10
    volumes:
      - prefect:/root/.prefect
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_PROFILE="default"
      - PREFECT_API_URL="http://127.0.0.1:4200/api"
    networks:
      - backend
      - frontend
    ports:
      - 4200:4200
    restart: always
    entrypoint: ["prefect", "server", "start"]
